"""Initial migration

Revision ID: 378024eeff93
Revises: 
Create Date: 2024-03-20 08:40:51.265143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378024eeff93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_users',
    sa.Column('vdID', sa.Integer(), nullable=False),
    sa.Column('vdNama', sa.String(length=64), nullable=False),
    sa.Column('vdSurel', sa.String(length=128), nullable=False),
    sa.Column('vdKodepas', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('vdID'),
    sa.UniqueConstraint('vdSurel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c_users')
    # ### end Alembic commands ###
