"""tabel gallery foreignkey user_id

Revision ID: 3e59bcb2c71c
Revises: 0da80ff3a9c3
Create Date: 2024-03-22 17:16:16.993007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e59bcb2c71c'
down_revision = '0da80ff3a9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_gallery',
    sa.Column('vdIDGbr', sa.Integer(), nullable=False),
    sa.Column('vdAlamatGbr', sa.String(length=256), nullable=False),
    sa.Column('vdKeterangan', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['c_users.vdIDUser'], ),
    sa.PrimaryKeyConstraint('vdIDGbr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c_gallery')
    # ### end Alembic commands ###
