"""edit foreign key vrGUser dan vrUGambar

Revision ID: 4791c87b722b
Revises: 3e59bcb2c71c
Create Date: 2024-03-23 06:03:22.302186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4791c87b722b'
down_revision = '3e59bcb2c71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_gallery',
    sa.Column('vdIDGbr', sa.Integer(), nullable=False),
    sa.Column('vdAlamatGbr', sa.String(length=256), nullable=False),
    sa.Column('vdKeterangan', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['c_users.vdIDUser'], ),
    sa.PrimaryKeyConstraint('vdIDGbr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c_gallery')
    # ### end Alembic commands ###
