"""vdID jadi vdIDUser dan vdIDTask. back_populate user dan tasks

Revision ID: 452ba00ec603
Revises: 378024eeff93
Create Date: 2024-03-21 17:19:49.981734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452ba00ec603'
down_revision = '378024eeff93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('c_tasks',
    # sa.Column('vdIDTask', sa.Integer(), nullable=False),
    # sa.Column('vdJudul', sa.String(length=64), nullable=True),
    # sa.Column('vdRinci', sa.String(length=1024), nullable=True),
    # sa.Column('vdStatus', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('vdIDTask')
    # )
    op.drop_table('_alembic_tmp_c_users')
    with op.batch_alter_table('c_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vdIDUser', sa.Integer()))
        batch_op.drop_column('vdID')
        batch_op.create_primary_key('c_users',['vdIDUser'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('c_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vdID', sa.INTEGER()))
        batch_op.drop_column('vdIDUser')

    op.drop_table('c_tasks')
    # ### end Alembic commands ###
